name: Build and Push Python Image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: zipvisa
  IMAGE_NAME: zipvisa-image
  GCR_REGION: us-west2  # Replace this with your preferred GCR region
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push to GCR
        env:
          REGISTRY: gcr.io
        run: |
          echo ${SERVICE_ACCOUNT_KEY} | gcloud auth activate-service-account --key-file=./zipvisa.json --account=zipvisa-docker-account@zipvisa.iam.gserviceaccount.com
          docker build -t $REGISTRY/$PROJECT_ID/$IMAGE_NAME:${GITHUB_SHA::8} -f $DOCKERFILE_PATH .
          docker push $REGISTRY/$PROJECT_ID/$IMAGE_NAME:${GITHUB_SHA::8}

      - name: Build and Push to Artifact Registry
        env:
          REGISTRY: us-west2-docker.pkg.dev
        run: |
          echo ${SERVICE_ACCOUNT_KEY} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker ${REGISTRY}/$PROJECT_ID
          docker tag $REGISTRY/$PROJECT_ID/$IMAGE_NAME:${GITHUB_SHA::8} ${REGISTRY}/$PROJECT_ID/$IMAGE_NAME:${GITHUB_SHA::8}
          docker push ${REGISTRY}/$PROJECT_ID/$IMAGE_NAME:${GITHUB_SHA::8}
