name: Build and Push Python Image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: zipvisa
  IMAGE_NAME: zipvisa-image
  GCR_REGION: us  # Replace this with your preferred GCR region
  DOCKERFILE_PATH: .
  AUTH_PATH: ./zipvisa.json

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Slack Notification on success
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: team-aws-lessons
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: 'https://media-exp1.licdn.com/dms/image/C5603AQH2WGnfEYTqtg/profile-displayphoto-shrink_200_200/0/1649421547143?e=1654732800&v=beta&t=_N2tkTJTMRGk-DqoFajb_xtqKDf8ih6g1k-wnL3tWHc'
          SLACK_MESSAGE: 'Testing Successful'
          SLACK_TITLE: Successful
          SLACK_USERNAME: team-aws-lessons
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK1 }}
      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: team-aws-lessons
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: 'https://media-exp1.licdn.com/dms/image/C5603AQH2WGnfEYTqtg/profile-displayphoto-shrink_200_200/0/1649421547143?e=1654732800&v=beta&t=_N2tkTJTMRGk-DqoFajb_xtqKDf8ih6g1k-wnL3tWHc'
          SLACK_MESSAGE: 'Testing Failed'
          SLACK_TITLE: Failed
          SLACK_USERNAME: team-aws-lessons
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK1 }}

      # - name: Configure Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     service_account_key: ${{ env.AUTH_PATH }}
      #     project_id: ${{ env.PROJECT_ID }}

      # - name: Build and Push to GCR
      #   env:
      #     REGISTRY: us.gcr.io
      #   run: |
      #     gcloud auth activate-service-account --key-file=${{ env.AUTH_PATH }}
      #     gcloud auth configure-docker --quiet
      #     docker build -t zipvisa-image .
      #     docker tag zipvisa-image us.gcr.io/zipvisa/zipvisa-image:zipvisa-image-tag
      #     docker push us.gcr.io/zipvisa/zipvisa-image:zipvisa-image-tag

      # - name: Push to Artifact Registry
      #   env:
      #     REGISTRY: us-west2-docker.pkg.dev
      #     REPOSITORY: zipvisa-api
      #   run: |
      #     gcloud auth activate-service-account --key-file=${{ env.AUTH_PATH }}
      #     gcloud auth configure-docker ${{ env.REGISTRY }} --quiet
      #     docker tag zipvisa-image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/zipvisa-image:zipvisa-image-tag
      #     docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/zipvisa-image:zipvisa-image-tag
