name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  # Set the GCR registry and Artifact Registry location
  GCR_REGISTRY: gcr.io
  ARTIFACT_REGISTRY_LOCATION: us-west2
  ARTIFACT_REGISTRY: us-west2-docker.pkg.dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

    - name: Login to GCR
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and push to GCR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.GCR_REGISTRY }}/${{ secrets.GCLOUD_PROJECT_ID }}/zipvisa-image:${{ github.sha }}
    
    - name: Build and push to Artifact Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ARTIFACT_REGISTRY }}/${{ secrets.GCLOUD_PROJECT_ID }}/zipvisa-api/zipvisa-image:${{ github.sha }}
